# Site settings
title: JH47
subheading: asd
header-img: img/home-bg.jpg
email: jhenson47@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://jh47.com"
twitter_username: HensonJamie
github_username:  jamiehenson
author: Jamie Henson

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

sass:
  style: compressed
