# Site settings
title: Jamie Henson
subheading: asd
header-img: img/home-bg.jpg
email: jhenson47@gmail.com
description: "Full-stack developer and multi-instrumentalist, currently immersed in the wonders of San Francisco."
baseurl: ""
url: "http://jh47.com"
twitter_username: HensonJamie
github_username:  jamiehenson
author: Jamie Henson

gems: [jekyll-paginate]

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

sass:
  style: compressed
